In [85]:
import numpy as np

# Tip 1 : Use properties

Properties are useful for:
- Making a function that behaves like an attribute
- Creating read-only attributes for instance
- Complex logic for when modifying attributes

In [86]:
class LinearRegression():
    def __init__(self,X,Y,gamma) -> None:
        self.X=X
        self.K=X.T@X+gamma*np.eye(X.shape[1])
        self.Y=Y
        self._gamma=gamma
    
    @property
    def n_samples(self):
        return self.X.shape[0]
    
    @property
    def K_inv(self):
        try:
            return self._kmat_inv
        except AttributeError:
            self._kmat_inv=np.linalg.inv(self.K)
            return self._kmat_inv
    
    @K_inv.deleter
    def K_inv(self):
        try:
            del self._kmat_inv
        except AttributeError:
            pass
    
    @property
    def gamma(self):
        return self._gamma
    
    @gamma.setter
    def gamma(self,new_gamma):
        self._gamma=new_gamma
        self.K=self.X.T@self.X+new_gamma*np.eye(self.X.shape[1])
        del self.K_inv




We can see here that properties beave like attributes, but the setter and deleter function work under the hood each time

In [87]:
LR=LinearRegression(np.random.rand(1000,10),np.random.rand(1000),1e-2)
LR.n_samples

1000

In [88]:
LR.gamma=1e-15
LR.K_inv[0,0]

0.010834957098308708

In [89]:
LR.gamma=100
LR.K_inv[0,0]

0.004931861931886988

# Tip 2: Define the standard functions

In [90]:
class LinearRegression2(LinearRegression):
    def __init__(self,X,Y,gamma):
        super().__init__(X,Y,gamma)
    
    def __call__(self,x):
        return np.dot(x,self.K_inv@self.X.T@self.Y)
    
    def __getitem__(self, index):
         return self.X[index],self.Y[index]
    
    def __repr__(self) -> str:
        return f'Linear Regression beta=(XX^T+{self.gamma}I)^-1X^TY\n ............. \n X: {self.X[:5,:5]}\n .......... \nY: {self.Y[:5]}\n ..............'


In [91]:
LR2=LinearRegression2(np.random.rand(1000,10),np.random.rand(1000),1e-2)


now LR2 is callable, subscriptable and printable

In [92]:
LR2

Linear Regression beta=(XX^T+0.01I)^-1X^TY
 ............. 
 X: [[0.26037574 0.3660719  0.13765819 0.228732   0.80595702]
 [0.57899256 0.37048779 0.14695577 0.06121121 0.63418116]
 [0.34062847 0.1514688  0.28753236 0.99152543 0.75056508]
 [0.50496055 0.22269646 0.48742886 0.18461113 0.30684443]
 [0.02747696 0.89395913 0.74568669 0.48736657 0.10545178]]
 .......... 
Y: [0.10912121 0.91579218 0.60959553 0.00539335 0.60413215]
 ..............

In [93]:
X_10,Y_10=LR2[10]
abs(Y_10-LR2(X_10))

0.3269153116700467